# -*- coding: utf-8 -*-
"""Job_Market_Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i76qz4EnJRwhqDnxP0_ZojLJAm4_hiDk
"""

import pandas as pd

df = pd.read_csv("naukri_com-job_sample.csv")

df.head()

df.info()

df.isnull().sum()

df = df.drop(columns=[
    "site_name",
    "numberofpositions",
    "uniq_id",
    "jobid"
])

df.columns

df["joblocation_address"] = df["joblocation_address"].str.split(",").str[0]
df["joblocation_address"] = df["joblocation_address"].str.replace("Bengaluru/Bangalore", "Bengaluru")
df["joblocation_address"] = df["joblocation_address"].str.strip()

df.rename(columns={"joblocation_address": "City"}, inplace=True)

df["City"].value_counts().head()

def extract_experience(exp):
    try:
        exp = exp.replace(" yrs", "")
        low, high = exp.split(" - ")
        return (int(low) + int(high)) / 2
    except:
        return None

df["Experience_Years"] = df["experience"].apply(extract_experience)

df.drop(columns=["experience"], inplace=True)

df["Experience_Years"].head()

df = df[~df["payrate"].str.contains("Not Disclosed", na=False)]

import re

def extract_salary(s):
    try:
        numbers = re.findall(r'\d+', s.replace(",", ""))
        if len(numbers) >= 2:
            low = int(numbers[0])
            high = int(numbers[1])
            return (low + high) / 2
        else:
            return None
    except:
        return None

df["Average_Salary"] = df["payrate"].apply(extract_salary)

df.drop(columns=["payrate"], inplace=True)

df["Average_Salary"].head()

df["Posting_Date"] = pd.to_datetime(df["Posting_Date"])

df["Year"] = df["Posting_Date"].dt.year
df["Month"] = df["Posting_Date"].dt.month
df["Month_Name"] = df["Posting_Date"].dt.month_name()

df.columns

df = df.rename(columns={
    "industry": "Industry",
    "skills": "Skill_Category",
    "jobtitle": "Job_Title"
})

df.columns

df = df.dropna(subset=[
    "City",
    "Average_Salary",
    "Experience_Years",
    "Industry",
    "Skill_Category"
])

df = df[(df["Average_Salary"] > 50000) & (df["Average_Salary"] < 5000000)]

df.shape

df.to_csv("job_market_dashboard_ready.csv", index=False)

from google.colab import files
files.download("job_market_dashboard_ready.csv")

df["education"] = df["education"].fillna("Not Specified")

df["education"].isnull().sum()

df.to_csv("job_market_dashboard.csv", index=False)

from google.colab import files
files.download("job_market_dashboard.csv")

